
CREATE TABLE IF NOT EXISTS `schools` (
  `id` varchar(50) NOT NULL PRIMARY KEY,
  `name` text,
  `nameAr` text,
  `location` text,
  `locationAr` text,
  `governorate` varchar(100),
  `governorateAr` varchar(100),
  `principal` text,
  `principalAr` text,
  `logo` text,
  `type` varchar(100),
  `mainImage` text,
  `gallery` text
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `schools` (`id`, `name`, `nameAr`, `location`, `locationAr`, `governorate`, `governorateAr`, `principal`, `principalAr`, `logo`, `type`, `mainImage`, `gallery`) VALUES ('1', 'Port Said School', 'مدرسة بورسعيد', 'Zamalek', 'الزمالك', 'Cairo', 'القاهرة', 'Dr. Ahmed Ali', '', 'https://picsum.photos/seed/school1/100/100', 'Languages', 'https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&w=800&q=80', '[]');
INSERT INTO `schools` (`id`, `name`, `nameAr`, `location`, `locationAr`, `governorate`, `governorateAr`, `principal`, `principalAr`, `logo`, `type`, `mainImage`, `gallery`) VALUES ('2', 'Nasr School for Girls', 'مدرسة النصر للبنات', 'Maadi', 'المعادي', 'Cairo', 'القاهرة', 'Mrs. Fatma Hassan', '', 'https://picsum.photos/seed/school2/100/100', 'American', 'https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&w=800&q=80', '[]');
INSERT INTO `schools` (`id`, `name`, `nameAr`, `location`, `locationAr`, `governorate`, `governorateAr`, `principal`, `principalAr`, `logo`, `type`, `mainImage`, `gallery`) VALUES ('3', 'Victoria College', 'كلية فيكتوريا', 'Victoria', 'فيكتوريا', 'Alexandria', 'الإسكندرية', 'Mr. John Smith', '', 'https://picsum.photos/seed/school3/100/100', 'Arabic', 'https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&w=800&q=80', '[]');
INSERT INTO `schools` (`id`, `name`, `nameAr`, `location`, `locationAr`, `governorate`, `governorateAr`, `principal`, `principalAr`, `logo`, `type`, `mainImage`, `gallery`) VALUES ('4', 'El Nasr Boys School', 'مدرسة النصر للبنين', 'Shatby', 'الشاطبي', 'Alexandria', 'الإسكندرية', 'Dr. Magdy Yacoub', '', 'https://picsum.photos/seed/school4/100/100', 'Languages', 'https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&w=800&q=80', '[]');
INSERT INTO `schools` (`id`, `name`, `nameAr`, `location`, `locationAr`, `governorate`, `governorateAr`, `principal`, `principalAr`, `logo`, `type`, `mainImage`, `gallery`) VALUES ('5', 'Language Schools of Mansoura', 'مدارس اللغات بالمنصورة', 'Dakahlia', 'الدقهلية', 'Dakahlia', 'الدقهلية', 'Dr. Mona Zaki', '', 'https://picsum.photos/seed/school5/100/100', 'Languages', 'https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&w=800&q=80', '[]');
INSERT INTO `schools` (`id`, `name`, `nameAr`, `location`, `locationAr`, `governorate`, `governorateAr`, `principal`, `principalAr`, `logo`, `type`, `mainImage`, `gallery`) VALUES ('6', 'Bakalos School', 'مدرسة باكالوس', 'Giza', 'الجيزة', 'Giza', 'الجيزة', 'Mr. Tarek Shawky', '', 'https://picsum.photos/seed/school6/100/100', 'Arabic', 'https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&w=800&q=80', '[]');
INSERT INTO `schools` (`id`, `name`, `nameAr`, `location`, `locationAr`, `governorate`, `governorateAr`, `principal`, `principalAr`, `logo`, `type`, `mainImage`, `gallery`) VALUES ('7', 'El Nasr Language School', 'مدرسة النصر للغات', 'Heliopolis', 'مصر الجديدة', 'Cairo', 'القاهرة', 'Ms. Laila Ahmed', '', 'https://picsum.photos/seed/school7/100/100', 'Languages', 'https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&w=800&q=80', '[]');
INSERT INTO `schools` (`id`, `name`, `nameAr`, `location`, `locationAr`, `governorate`, `governorateAr`, `principal`, `principalAr`, `logo`, `type`, `mainImage`, `gallery`) VALUES ('8', 'Misr Language School', 'مدرسة مصر للغات', 'Pyramids', 'الأهرام', 'Giza', 'الجيزة', 'Dr. Ibrahim Kamel', '', 'https://picsum.photos/seed/school8/100/100', 'American', 'https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&w=800&q=80', '[]');
INSERT INTO `schools` (`id`, `name`, `nameAr`, `location`, `locationAr`, `governorate`, `governorateAr`, `principal`, `principalAr`, `logo`, `type`, `mainImage`, `gallery`) VALUES ('9', 'Suez Canal School', 'مدرسة قناة السويس', 'Maadi', 'المعادي', 'Cairo', 'القاهرة', 'Mrs. Sanaa Mansour', '', 'https://picsum.photos/seed/school9/100/100', 'Languages', 'https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&w=800&q=80', '[]');
INSERT INTO `schools` (`id`, `name`, `nameAr`, `location`, `locationAr`, `governorate`, `governorateAr`, `principal`, `principalAr`, `logo`, `type`, `mainImage`, `gallery`) VALUES ('10', 'Modern Education School', 'مدرسة التربية الحديثة', 'New Cairo', 'القاهرة الجديدة', 'Cairo', 'القاهرة', 'Mr. Khaled El-Nabawy', '', 'https://picsum.photos/seed/school10/100/100', 'American', 'https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&w=800&q=80', '[]');
INSERT INTO `schools` (`id`, `name`, `nameAr`, `location`, `locationAr`, `governorate`, `governorateAr`, `principal`, `principalAr`, `logo`, `type`, `mainImage`, `gallery`) VALUES ('11', 'Tanta Language School', 'مدرسة طنطا للغات', 'Tanta', 'طنطا', 'Gharbia', 'الغربية', 'Ms. Nadia Lotfy', '', 'https://picsum.photos/seed/school11/100/100', 'Languages', 'https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&w=800&q=80', '[]');
INSERT INTO `schools` (`id`, `name`, `nameAr`, `location`, `locationAr`, `governorate`, `governorateAr`, `principal`, `principalAr`, `logo`, `type`, `mainImage`, `gallery`) VALUES ('12', 'Mansoura Victoria School', 'مدرسة فيكتوريا بالمنصورة', 'Mansoura', 'المنصورة', 'Dakahlia', 'الدقهلية', 'Mr. Ahmed Helmy', '', 'https://picsum.photos/seed/school12/100/100', 'Arabic', 'https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&w=800&q=80', '[]');
INSERT INTO `schools` (`id`, `name`, `nameAr`, `location`, `locationAr`, `governorate`, `governorateAr`, `principal`, `principalAr`, `logo`, `type`, `mainImage`, `gallery`) VALUES ('13', 'Alexandria International School', 'مدرسة الإسكندرية الدولية', 'Montaza', 'المنتزه', 'Alexandria', 'الإسكندرية', 'Dr. Sarah Jenkins', '', 'https://picsum.photos/seed/school13/100/100', 'American', 'https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&w=800&q=80', '[]');
INSERT INTO `schools` (`id`, `name`, `nameAr`, `location`, `locationAr`, `governorate`, `governorateAr`, `principal`, `principalAr`, `logo`, `type`, `mainImage`, `gallery`) VALUES ('14', 'Giza National School', 'مدرسة الجيزة القومية', 'Dokki', 'الدقي', 'Giza', 'الجيزة', 'Mr. Mahmoud Yassin', '', 'https://picsum.photos/seed/school14/100/100', 'Arabic', 'https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&w=800&q=80', '[]');
INSERT INTO `schools` (`id`, `name`, `nameAr`, `location`, `locationAr`, `governorate`, `governorateAr`, `principal`, `principalAr`, `logo`, `type`, `mainImage`, `gallery`) VALUES ('15', 'Zamalek Language School', 'مدرسة الزمالك للغات', 'Zamalek', 'الزمالك', 'Cairo', 'القاهرة', 'Ms. Yousra', '', 'https://picsum.photos/seed/school15/100/100', 'Languages', 'https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&w=800&q=80', '[]');
INSERT INTO `schools` (`id`, `name`, `nameAr`, `location`, `locationAr`, `governorate`, `governorateAr`, `principal`, `principalAr`, `logo`, `type`, `mainImage`, `gallery`) VALUES ('16', 'Agouza National School', 'مدرسة العجوزة القومية', 'Agouza', 'العجوزة', 'Giza', 'الجيزة', 'Mr. Adel Imam', '', 'https://picsum.photos/seed/school16/100/100', 'Arabic', 'https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&w=800&q=80', '[]');
INSERT INTO `schools` (`id`, `name`, `nameAr`, `location`, `locationAr`, `governorate`, `governorateAr`, `principal`, `principalAr`, `logo`, `type`, `mainImage`, `gallery`) VALUES ('17', 'Nasr City Language School', 'مدرسة مدينة نصر للغات', 'Nasr City', 'مدينة نصر', 'Cairo', 'القاهرة', 'Dr. Mona El-Shazly', '', 'https://picsum.photos/seed/school17/100/100', 'Languages', 'https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&w=800&q=80', '[]');
INSERT INTO `schools` (`id`, `name`, `nameAr`, `location`, `locationAr`, `governorate`, `governorateAr`, `principal`, `principalAr`, `logo`, `type`, `mainImage`, `gallery`) VALUES ('18', 'Maadi British School', 'المدرسة البريطانية بالمعادي', 'Maadi', 'المعادي', 'Cairo', 'القاهرة', 'Mr. David Miller', '', 'https://picsum.photos/seed/school18/100/100', 'American', 'https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&w=800&q=80', '[]');
INSERT INTO `schools` (`id`, `name`, `nameAr`, `location`, `locationAr`, `governorate`, `governorateAr`, `principal`, `principalAr`, `logo`, `type`, `mainImage`, `gallery`) VALUES ('19', 'Shubra National School', 'مدرسة شبرا القومية', 'Shubra', 'شبرا', 'Cairo', 'القاهرة', 'Ms. Karima Mokhtar', '', 'https://picsum.photos/seed/school19/100/100', 'Arabic', 'https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&w=800&q=80', '[]');
INSERT INTO `schools` (`id`, `name`, `nameAr`, `location`, `locationAr`, `governorate`, `governorateAr`, `principal`, `principalAr`, `logo`, `type`, `mainImage`, `gallery`) VALUES ('20', 'Heliopolis International', 'مدرسة مصر الجديدة الدولية', 'Heliopolis', 'مصر الجديدة', 'Cairo', 'القاهرة', 'Dr. Amr Adeeb', '', 'https://picsum.photos/seed/school20/100/100', 'American', 'https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&w=800&q=80', '[]');
INSERT INTO `schools` (`id`, `name`, `nameAr`, `location`, `locationAr`, `governorate`, `governorateAr`, `principal`, `principalAr`, `logo`, `type`, `mainImage`, `gallery`) VALUES ('21', 'El Mansoura Boys', 'مدرسة المنصورة للبنين', 'Talkha', 'طلخا', 'Dakahlia', 'الدقهلية', 'Mr. Mohamed Sobhi', '', 'https://picsum.photos/seed/school21/100/100', 'Languages', 'https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&w=800&q=80', '[]');
INSERT INTO `schools` (`id`, `name`, `nameAr`, `location`, `locationAr`, `governorate`, `governorateAr`, `principal`, `principalAr`, `logo`, `type`, `mainImage`, `gallery`) VALUES ('22', 'Alexandria Girls College', 'كلية الإسكندرية للبنات', 'Saba Pasha', 'سابا باشا', 'Alexandria', 'الإسكندرية', 'Ms. Hend Rostom', '', 'https://picsum.photos/seed/school22/100/100', 'Arabic', 'https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&w=800&q=80', '[]');
INSERT INTO `schools` (`id`, `name`, `nameAr`, `location`, `locationAr`, `governorate`, `governorateAr`, `principal`, `principalAr`, `logo`, `type`, `mainImage`, `gallery`) VALUES ('23', 'Tanta American School', 'مدرسة طنطا الأمريكية', 'Tanta', 'طنطا', 'Gharbia', 'الغربية', 'Mr. Robert Wilson', '', 'https://picsum.photos/seed/school23/100/100', 'American', 'https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&w=800&q=80', '[]');
INSERT INTO `schools` (`id`, `name`, `nameAr`, `location`, `locationAr`, `governorate`, `governorateAr`, `principal`, `principalAr`, `logo`, `type`, `mainImage`, `gallery`) VALUES ('24', 'Giza Language Academy', 'أكاديمية الجيزة للغات', 'Mohandessin', 'المهندسين', 'Giza', 'الجيزة', 'Ms. Ghada Abdel Razek', '', 'https://picsum.photos/seed/school24/100/100', 'Languages', 'https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&w=800&q=80', '[]');
INSERT INTO `schools` (`id`, `name`, `nameAr`, `location`, `locationAr`, `governorate`, `governorateAr`, `principal`, `principalAr`, `logo`, `type`, `mainImage`, `gallery`) VALUES ('25', 'Sheraton National School', 'مدرسة شيراتون القومية', 'Sheraton', 'شيراتون', 'Cairo', 'القاهرة', 'Mr. Ahmed Mekky', '', 'https://picsum.photos/seed/school25/100/100', 'Arabic', 'https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&w=800&q=80', '[]');

CREATE TABLE IF NOT EXISTS `news` (
  `id` varchar(50) NOT NULL PRIMARY KEY,
  `title` text,
  `titleAr` text,
  `date` text,
  `summary` text,
  `summaryAr` text,
  `image` text,
  `content` longtext,
  `contentAr` longtext,
  `highlightTitle` varchar(255),
  `highlightTitleAr` varchar(255),
  `highlightContent` longtext,
  `highlightContentAr` longtext,
  `featured` tinyint(1) DEFAULT 0,
  `published` tinyint(1) DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `news` (`id`, `title`, `titleAr`, `date`, `summary`, `summaryAr`, `image`, `content`, `contentAr`, `highlightTitle`, `highlightTitleAr`, `highlightContent`, `highlightContentAr`, `published`, `featured`) VALUES ('1',  'NIS National Sports Day 2024',  'اليوم الرياضي للمعاهد القومية ٢٠٢٤',  '2024-03-15',  'Over 5, 000 students participated in our multi-governorate sports festival held at the Olympic Center.',  'شارك أكثر من ٥٠٠٠ طالب في مهرجاننا الرياضي الذي أقيم في المركز الأوليمبي.',  'https://images.unsplash.com/photo-1529900748604-07564a03e7a6?auto=format&fit=crop&w=800&q=80',  '', '', '', '', '', '', 1, 0);
INSERT INTO `news` (`id`, `title`, `titleAr`, `date`, `summary`, `summaryAr`, `image`, `content`, `contentAr`, `highlightTitle`, `highlightTitleAr`, `highlightContent`, `highlightContentAr`, `published`, `featured`) VALUES ('2',  'New Science Labs in Alexandria',  'مختبرات علوم جديدة في الإسكندرية',  '2024-03-12',  'Victoria College inaugurates state-of-the-art STEM laboratories to enhance practical learning.',  'كلية فيكتوريا تفتتح مختبرات STEM الحديثة لتعزيز التعلم العملي.',  'https://images.unsplash.com/photo-1532094349884-543bc11b234d?auto=format&fit=crop&w=800&q=80',  '',  '', '', '', '', '', 1, 0);
INSERT INTO `news` (`id`, `title`, `titleAr`, `date`, `summary`, `summaryAr`, `image`, `content`, `contentAr`, `highlightTitle`, `highlightTitleAr`, `highlightContent`, `highlightContentAr`, `published`, `featured`) VALUES ('3',  'Arabic Calligraphy Competition',  'مسابقة الخط العربي',  '2024-03-10',  'Celebrating our rich heritage through the annual NIS calligraphy championship for middle schoolers.',  'الاحتفال بتراثنا الغني من خلال بطولة الخط السنوية لطلاب المرحلة الإعدادية.',  'https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=800&q=80',  '',  '', '', '', '', '', 1, 0);
INSERT INTO `news` (`id`, `title`, `titleAr`, `date`, `summary`, `summaryAr`, `image`, `content`, `contentAr`, `highlightTitle`, `highlightTitleAr`, `highlightContent`, `highlightContentAr`, `published`, `featured`) VALUES ('4',  'Teacher Excellence Awards',  'جوائز التميز للمعلمين',  '2024-03-08',  'Recognizing the dedication of our 8, 500+ educators at the annual NIS Cairo summit.',  'تكريم جهود أكثر من ٨٥٠٠ معلم في قمة المعاهد القومية السنوية بالقاهرة.',  'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?auto=format&fit=crop&w=800&q=80',  '', '', '', '', '', '', 1, 0);
INSERT INTO `news` (`id`, `title`, `titleAr`, `date`, `summary`, `summaryAr`, `image`, `content`, `contentAr`, `highlightTitle`, `highlightTitleAr`, `highlightContent`, `highlightContentAr`, `published`, `featured`) VALUES ('5',  'Robotics Team Wins Bronze',  'فريق الروبوتات يحصد البرونزية',  '2024-03-05',  'The Giza National School robotics team secured 3rd place in the international FIRST LEGO League.',  'حقق فريق الروبوتات بمدرسة الجيزة القومية المركز الثالث في مسابقة FIRST LEGO League الدولية.',  'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&w=800&q=80',  '',  '', '', '', '', '', 1, 0);
INSERT INTO `news` (`id`, `title`, `titleAr`, `date`, `summary`, `summaryAr`, `image`, `content`, `contentAr`, `highlightTitle`, `highlightTitleAr`, `highlightContent`, `highlightContentAr`, `published`, `featured`) VALUES ('6',  'Summer Camps Enrollment Open',  'فتح باب التسجيل في المعسكرات الصيفية',  '2024-03-01',  'Diverse summer programs ranging from coding to art are now available across all NIS campuses.',  'برامج صيفية متنوعة تتراوح من البرمجة إلى الفنون متاحة الآن في جميع فروعنا.',  'https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&w=800&q=80',  '',  '', '', '', '', '', 1, 0);
INSERT INTO `news` (`id`, `title`, `titleAr`, `date`, `summary`, `summaryAr`, `image`, `content`, `contentAr`, `highlightTitle`, `highlightTitleAr`, `highlightContent`, `highlightContentAr`, `published`, `featured`) VALUES ('7',  'IGCSE Top Achievers Ceremony',  'حفل تكريم أوائل الـ IGCSE',  '2024-02-25',  'Honoring our students who achieved world-highest scores in the Cambridge IGCSE examinations.',  'تكريم طلابنا الذين حققوا أعلى الدرجات العالمية في امتحانات كامبريدج IGCSE.',  'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&w=800&q=80',  '',  '', '', '', '', '', 1, 0);
INSERT INTO `news` (`id`, `title`, `titleAr`, `date`, `summary`, `summaryAr`, `image`, `content`, `contentAr`, `highlightTitle`, `highlightTitleAr`, `highlightContent`, `highlightContentAr`, `published`, `featured`) VALUES ('8',  'Sustainable Campus Initiative',  'مبادرة الحرم المدرسي المستدام',  '2024-02-20',  'NIS Mansoura launches the first solar-powered primary school section in the Delta region.',  'المعاهد القومية بالمنصورة تطلق أول قسم ابتدائي يعمل بالطاقة الشمسية في منطقة الدلتا.',  'https://images.unsplash.com/photo-1509391366360-2e959784a276?auto=format&fit=crop&w=800&q=80',  '',  '', '', '', '', '', 1, 0);
INSERT INTO `news` (`id`, `title`, `titleAr`, `date`, `summary`, `summaryAr`, `image`, `content`, `contentAr`, `highlightTitle`, `highlightTitleAr`, `highlightContent`, `highlightContentAr`, `published`, `featured`) VALUES ('9',  'Chess Tournament Finals',  'نهائيات بطولة الشطرنج',  '2024-02-15',  'The final showdown of the inter-school chess championship takes place in Maadi this weekend.',  'المواجهة النهائية لبطولة الشطرنج بين المدارس تقام في المعادي هذا الأسبوع.',  'https://images.unsplash.com/photo-1529699211952-734e80c4d42b?auto=format&fit=crop&w=800&q=80',  '',  '', '', '', '', '', 1, 0);
INSERT INTO `news` (`id`, `title`, `titleAr`, `date`, `summary`, `summaryAr`, `image`, `content`, `contentAr`, `highlightTitle`, `highlightTitleAr`, `highlightContent`, `highlightContentAr`, `published`, `featured`) VALUES ('10',  'Community Service Week',  'أسبوع الخدمة المجتمعية',  '2024-02-10',  'Students from 40+ schools joined forces to plant 10, 000 trees across 5 governorates.',  'تعاون طلاب من أكثر من ٤٠ مدرسة لزراعة ١٠, ٠٠٠ شجرة في ٥ محافظات.',  'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&w=800&q=80', '', '', '', '', '', '', 1, 0);
INSERT INTO `news` (`id`, `title`, `titleAr`, `date`, `summary`, `summaryAr`, `image`, `content`, `contentAr`, `highlightTitle`, `highlightTitleAr`, `highlightContent`, `highlightContentAr`, `published`, `featured`) VALUES ('11',  'Digital Transformation Phase 2',  'المرحلة الثانية من التحول الرقمي',  '2024-02-05',  'All NIS classrooms are now equipped with interactive smart boards and high-speed fiber optics.',  'تم تجهيز جميع فصولنا بسبورات ذكية تفاعلية وألياف ضوئية عالية السرعة.',  'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&w=800&q=80',  '',  '', '', '', '', '', 1, 0);
INSERT INTO `news` (`id`, `title`, `titleAr`, `date`, `summary`, `summaryAr`, `image`, `content`, `contentAr`, `highlightTitle`, `highlightTitleAr`, `highlightContent`, `highlightContentAr`, `published`, `featured`) VALUES ('12',  'Music and Arts Festival',  'مهرجان الموسيقى والفنون',  '2024-02-01',  'A showcase of Egyptian talent at the Cairo Opera House featuring our NIS symphony orchestra.',  'عرض للمواهب المصرية في دار الأوبرا المصرية يضم أوركسترا السيمفوني للمعاهد القومية.',  'https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?auto=format&fit=crop&w=800&q=80',  '',  '', '', '', '', '', 1, 0);

CREATE TABLE IF NOT EXISTS `jobs` (
  `id` varchar(50) NOT NULL PRIMARY KEY,
  `title` text,
  `titleAr` text,
  `department` varchar(100),
  `departmentAr` varchar(100),
  `location` text,
  `locationAr` text,
  `type` varchar(50),
  `typeAr` varchar(50),
  `description` text,
  `descriptionAr` text
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `jobs` (`id`, `title`, `titleAr`, `department`, `departmentAr`, `location`, `locationAr`, `type`, `typeAr`, `description`, `descriptionAr`) VALUES ('1', 'Mathematics Teacher (IGCSE)', 'مدرس رياضيات (IGCSE)', 'Academic', 'أكاديمي', 'Zamalek, Cairo', 'الزمالك، القاهرة', 'Full-time', 'دوام كامل', 'Seeking an experienced math teacher for our international section.', 'مطلوب مدرس رياضيات ذو خبرة للقسم الدولي.');
INSERT INTO `jobs` (`id`, `title`, `titleAr`, `department`, `departmentAr`, `location`, `locationAr`, `type`, `typeAr`, `description`, `descriptionAr`) VALUES ('2', 'School Counselor', 'مرشد طلابي', 'Student Services', 'خدمات الطلاب', 'Victoria, Alexandria', 'فيكتوريا، الإسكندرية', 'Full-time', 'دوام كامل', 'Experienced counselor to support student mental health and academic guidance.', 'مرشد ذو خبرة لدعم الصحة النفسية للطلاب والإرشاد الأكاديمي.');
INSERT INTO `jobs` (`id`, `title`, `titleAr`, `department`, `departmentAr`, `location`, `locationAr`, `type`, `typeAr`, `description`, `descriptionAr`) VALUES ('3', 'Administrative Assistant', 'مساعد إداري', 'Admin', 'إدارة', 'Maadi, Cairo', 'المعادي، القاهرة', 'Part-time', 'دوام جزئي', 'Assisting the principal office with daily administrative tasks.', 'مساعدة مكتب المدير في المهام الإدارية اليومية.');
INSERT INTO `jobs` (`id`, `title`, `titleAr`, `department`, `departmentAr`, `location`, `locationAr`, `type`, `typeAr`, `description`, `descriptionAr`) VALUES ('4', 'Physical Education Coach', 'مدرب تربية رياضية', 'Sports', 'أنشطة رياضية', 'Tanta, Gharbia', 'طنطا، الغربية', 'Full-time', 'دوام كامل', 'Lead sports programs and manage inter-school athletic competitions.', 'قيادة البرامج الرياضية وإدارة المسابقات الرياضية بين المدارس.');
INSERT INTO `jobs` (`id`, `title`, `titleAr`, `department`, `departmentAr`, `location`, `locationAr`, `type`, `typeAr`, `description`, `descriptionAr`) VALUES ('5', 'English Literature Specialist', 'أخصائي أدب إنجليزي', 'Academic', 'أكاديمي', 'Nasr City, Cairo', 'مدينة نصر، القاهرة', 'Full-time', 'دوام كامل', 'Advanced literature instruction for secondary levels.', 'تعليم متقدم للأدب للمراحل الثانوية.');

CREATE TABLE IF NOT EXISTS `settings` (
  `setting_key` varchar(100) NOT NULL PRIMARY KEY,
  `setting_value` longtext
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `settings` (`setting_key`, `setting_value`) VALUES ('heroSlides', '[{"id":1,"title":"Nurturing Global Leaders","titleAr":"تنشئة قادة عالميين","subtitle":"Legacy of Excellence","subtitleAr":"إرث من التميز","description":"Empowering the next generation with world-class education and values.","descriptionAr":"تمكين الجيل القادم من خلال تعليم وقيم ذات مستوى عالمي.","image":"/nano-banana-1771792169108.webp"},{"id":2,"title":"Excellence in Education","titleAr":"التميز في التعليم","subtitle":"Leading National Institutes in Egypt","subtitleAr":"المعاهد القومية الرائدة في مصر","description":"Empowering future generations with knowledge and values.","descriptionAr":"تمكين أجيال المستقبل بالمعرفة والقيم.","image":"/nano-banana-1771778144311.png"},{"id":3,"title":"Modern Learning","titleAr":"تعلم حديث","subtitle":"Advanced Curriculum & Facilities","subtitleAr":"مناهج ومرافق متطورة","description":"Preparing students for a globalized world.","descriptionAr":"إعداد الطلاب لعالم معولم.","image":"/nano-banana-1771806330134.png"}]');
INSERT INTO `settings` (`setting_key`, `setting_value`) VALUES ('aboutData', '{"name":"Ahmed Eid","nameAr":"أحمد عيد","role":"Chairman of NIS","roleAr":"رئيس المعاهد القومية","desc":"Leading the future of national education in Egypt through excellence and innovation.","descAr":"قيادة مستقبل التعليم القومي في مصر من خلال التميز والابتكار.","quote":"Education is the most powerful weapon which you can use to change the world.","quoteAr":"التعليم هو أقوى سلاح يمكنك استخدامه لتغيير العالم.","points":["40+ Years of Excellence","Modern Curriculum","Expert Faculty","Advanced Facilities"],"pointsAr":["أكثر من ٤٠ عاماً من التميز","مناهج حديثة","أعضاء هيئة تدريس خبراء","مرافق متقدمة"],"chairmanImage":"https://images.unsplash.com/photo-1560250097-0b93528c311a?q=80&w=600&auto=format&fit=crop","storyTitle":"Crafting the Future Since 1995","storyTitleAr":"صياغة المستقبل منذ عام ١٩٩٥","storyDesc":"Our journey began with a simple yet profound vision: to provide world-class education that respects our national roots while embracing global innovation.","storyDescAr":"بدأت رحلتنا برؤية بسيطة ولكن عميقة: تقديم تعليم عالمي يحترم جذورنا الوطنية مع تبني الابتكار العالمي.","missionTitle":"Our Mission","missionTitleAr":"رسالتنا","missionDesc":"To empower students with the knowledge, skills, and values needed to thrive in an ever-changing world, fostering a new generation of Egyptian leaders.","missionDescAr":"تمكين الطلاب بالمعرفة والمهارات والقيم اللازمة للازدهار في عالم دائم التغير، ورعاية جيل جديد من القادة المصريين.","visionTitle":"Our Vision","visionTitleAr":"رؤيتنا","visionDesc":"To be the benchmark for educational excellence in Egypt, recognized for producing graduates who are intellectually curious and socially responsible.","visionDescAr":"أن نكون المعيار للتميز التعليمي في مصر، والمعترف بنا في تخريج طلاب يتسمون بالفضول الفكري والمسؤولية الاجتماعية.","values":[{"title":"Excellence","titleAr":"التميز","desc":"Striving for the highest standards in everything we do.","descAr":"السعي لتحقيق أعلى المعايير في كل ما نقوم به."},{"title":"Innovation","titleAr":"الابتكار","desc":"Embracing new ideas and creative problem solving.","descAr":"تبني الأفكار الجديدة وحل المشكلات بطرق إبداعية."},{"title":"Integrity","titleAr":"النزاهة","desc":"Maintaining honest and ethical conduct at all times.","descAr":"الحفاظ على السلوك الصادق والأخلاقي في جميع الأوقات."},{"title":"Community","titleAr":"المجتمع","desc":"Fostering a supportive and inclusive learning environment.","descAr":"تعزيز بيئة تعليمية داعمة وشاملة للجميع."}]}');
INSERT INTO `settings` (`setting_key`, `setting_value`) VALUES ('jobApplications', '[]');
INSERT INTO `settings` (`setting_key`, `setting_value`) VALUES ('complaints', '[]');
INSERT INTO `settings` (`setting_key`, `setting_value`) VALUES ('contactMessages', '[]');
INSERT INTO `settings` (`setting_key`, `setting_value`) VALUES ('stats', '{"journeyInNumbers":"Our Journey in Numbers","journeyInNumbersAr":"رحلتنا في أرقام","items":[{"number":"40+","label":"Educational Institutions","labelAr":"مؤسسة تعليمية","color":"bg-rose-400"},{"number":"50k+","label":"Students Enrolled","labelAr":"طالب وطالبة","color":"bg-sky-300"},{"number":"8.5k+","label":"Expert Educators","labelAr":"معلم خبير","color":"bg-amber-300"},{"number":"5","label":"Decades of Legacy","labelAr":"عقود من العطاء","color":"bg-emerald-300"}]}');
INSERT INTO `settings` (`setting_key`, `setting_value`) VALUES ('homeData', '{"trustedTitle":"Trusted by Generations of","trustedTitleAr":"أجيال تثق في","trustedHighlight":"Egyptian Families","trustedHighlightAr":"العائلات المصرية","trustedDesc":"Providing high-quality national education that builds character and prepares students for a successful future.","trustedDescAr":"تقديم تعليم قومي عالي الجودة يبني الشخصية ويعد الطلاب لمستقبل ناجح.","trustedCTA":"Discover Our Schools","trustedCTAAr":"اكتشف مدارسنا","gatewayTitle":"Your Gateway to","gatewayTitleAr":"بوابتك إلى","gatewayHighlight":"Educational Excellence","gatewayHighlightAr":"التميز التعليمي","gatewayDesc":"Join thousands of students across Egypt in our network of specialized national institutes.","gatewayDescAr":"انضم إلى آلاف الطلاب في جميع أنحاء مصر في شبكة معاهدنا القومية المتخصصة.","gatewayCTA":"View Map","gatewayCTAAr":"عرض الخريطة","mapImage":"/nano-banana-17717977008341.webp","ctaTitle":"Join the NIS Family Today","ctaTitleAr":"انضم لعائلة المعاهد القومية اليوم","ctaDesc":"Become part of Egypt''s leading educational network and shape your child''s future.","ctaDescAr":"كن جزءاً من شبكة التعليم الرائدة في مصر وشكل مستقبل طفلك.","ctaButton":"Register Interest","ctaButtonAr":"سجل اهتمامك"}');
INSERT INTO `settings` (`setting_key`, `setting_value`) VALUES ('partners', '[{"id":"1","name":"Partner 1","logo":"/image copy.png"},{"id":"2","name":"Partner 2","logo":"/image copy.png"},{"id":"3","name":"Partner 3","logo":"/image copy.png"},{"id":"4","name":"Partner 4","logo":"/image copy.png"}]');
INSERT INTO `settings` (`setting_key`, `setting_value`) VALUES ('galleryImages', '["https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&w=600&q=80","https://images.unsplash.com/photo-1507842217343-583bb7270b66?auto=format&fit=crop&w=600&q=80","https://images.unsplash.com/photo-1532094349884-543bc11b234d?auto=format&fit=crop&w=600&q=80","https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&w=600&q=80"]');
INSERT INTO `settings` (`setting_key`, `setting_value`) VALUES ('formSettings', '{"contactFormTitle":"Get in Touch","contactFormTitleAr":"تواصل معنا","contactFormDesc":"We are here to answer your questions and help you in any way we can.","contactFormDescAr":"نحن هنا للإجابة على أسئلتك ومساعدتك بأي طريقة ممكنة.","jobFormTitle":"Join Our Team","jobFormTitleAr":"انضم إلى فريقنا","jobFormDesc":"Fill out the form below to apply for your dream job at NIS.","jobFormDescAr":"املأ النموذج أدناه للتقدم لوظيفة أحلامك في المعاهد القومية."}');
INSERT INTO `settings` (`setting_key`, `setting_value`) VALUES ('contactData', '{"address":"123 Education St, Cairo, Egypt","addressAr":"١٢٣ شارع التعليم، القاهرة، مصر","phone":"+20 123 456 7890","email":"info@nis.edu.eg","workingHours":"Sunday - Thursday: 8:00 AM - 3:00 PM","workingHoursAr":"الأحد - الخميس: ٨:٠٠ صباحاً - ٣:٠٠ مساءً","facebook":"https://facebook.com","twitter":"https://twitter.com","instagram":"https://instagram.com","linkedin":"https://linkedin.com","footerDesc":"The largest educational organization in Egypt, overseeing excellence in national and international schooling for over 60 years.","footerDescAr":"أكبر مؤسسة تعليمية في مصر، تشرف على التميز في التعليم القومي والدولي لأكثر من 60 عاماً."}');
